spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/dingsheng?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
# 配置druid数据源
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bilibili.datasource.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


